= Git Workflow
Meredith Winchell, Jackie McCarthy, and Nate Alberda
:description: The document's description. 
:url-repo: https://github.com/mwinchell/PTW_320_Beta_Project.git

== Pre-requisites
Before starting, ensure you have the following installed:
* https://github.com/git-guides/install-git [Git^]
* A text editor or IDE of your choice (e.g., Visual Studio Code)
* Access to a project repository

== Introduction
This document outlines the Git workflow starting from the inital setup of a project repository to the iterative process of pushing your commits and pulling from GitHub. It is designed to help you understand how to effectively use Git for version control in your technical writing projects. This is following the "Write the Docs" philosophy, which emphasizes collaboration and iterative development between writers and developers. Git is a powerful tool that allows you to track changes, collaborate with others, and manage your project efficiently.

== Setting Up Your Project Repository
To begin, you need to set up your project repository. This involves creating a new repository on GitHub and cloning it to your local machine. Follow these steps:
1. Go to GitHub and create a new repository. Make sure to initialize it with a README file. //screenshot of creating a new repository
    - Click on the "New" button in the repositories section.
    - Fill in the repository name and description.
    - Choose visibility (public or private)
    - Select "Create repository"
2. Clone the repository to your local machine using the command:
   ```
   git clone    <repository-url>
   ```
3. Navigate to the cloned repository directory:
   ```
   cd <repository-name>
   ```
4. Open the repository in your text editor or IDE.

== Making Changes and Committing